name: Dispatch Site Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ADVENTOFCODE_API_KEY }}
          repository: rogerahuntley/adventofcode
          event-type: solution_published
